import java.text.SimpleDateFormat
version = ""
imageName = "backend"
devTag = "0.0-0"
CICD_PROJECT = "ci-cd"
DEV_PROJECT = "dev"
selectTag = ""
releaseTag = ""
tag = ""
UAT_PROJECT = "uat"

node('dotnet-31') {

  stage('Checkout Source') {
	checkout scm
  }
  
  stage('Prepare Variable') {
	script {
	  def dateFormat = new SimpleDateFormat("yyyyMMdd")
      def date = new Date()
      def releaseDate = (dateFormat.format(date))
      tag = releaseDate + "-" + env.BUILD_NUMBER
	  echo "tag: ${tag}"
	}
  }

  stage('Choose UAT Version') {
    script {
      openshift.withCluster() {
        namespace = openshift.project()
        def tags = openshift.selector("istag")
          .objects()
          .collect {
            it.metadata.name
          }
          .findAll {
            it ==~ /^backend:([0-9]+)\.([0-9]+)\.([0-9]+)\-([0-9]+)$/
            //it.startsWith 'backend:([0-9]+)\.([0-9]+)\.([0-9]+)\-([0-9]+)'
          }
          .collect {
            it.replaceAll(/backend:(.*)/, "\$1")
          }
          .sort()
        timeout(5) {
          selectTag = input(
            ok: "Deploy UAT",
            message: "Enter release version to promote to UAT",
            parameters: [
              choice(
                choices: tags.join('\n'),
                description: '',
                name: 'Release Version'
              )
            ]
          )
        }
      }
      println "selectTag = ${selectTag}"
      version = selectTag.split('-')[0]
      println "version = ${version}"
      println "tag = ${tag}"
      releaseTag = version + "-" + tag
      println "releaseTag = ${releaseTag}"
    }
  }

  stage('Release Image to Repository') {
    script {
      openshift.withCluster() {
        openshift.withProject("${CICD_PROJECT}") {
          println "Releasing image  ${imageName}:${selectTag} to Repository"
          openshift.tag("${imageName}:${selectTag}", "${imageName}:${releaseTag}")
        }
      }
    }
  }
	
  stage('Tear-Down Stage') {
    script {
      openshift.withCluster() {
        openshift.withProject("${UAT_PROJECT}") {
          println "Tear-Down project ${UAT_PROJECT}"
          openshift.raw("delete all -l app=${imageName}")
        }
      }
    }
  }

  stage('Create Service') {
    script {
      openshift.withCluster() {
        openshift.withProject("${UAT_PROJECT}") {
          def template = './bin/backend-svc-stage.yaml'
          openshift.apply(
            openshift.process("-f", template)
          )
        }
      }
    }
  }
    
  stage('Create Route') {
    script {
      openshift.withCluster() {
        openshift.withProject("${UAT_PROJECT}") {
          def template = './bin/backend-route-stage.yaml'
          openshift.apply(
            openshift.process("-f", template)
          )
        }
      }
    }
  }
    
  stage('Create Deployment Config') {
    println "Deploy to: ${UAT_PROJECT}"
    println "IMAGE_TAG = ${releaseTag}"
    script {
      openshift.withCluster() {
        openshift.withProject("${UAT_PROJECT}") {
          def template = './bin/backend-dc-stage.yaml'
          openshift.apply(
            openshift.process(
              "-f", template,
              "-p", "IMAGE_TAG=${releaseTag}",
              "-p", "APP_VERSION=${version}"
            )
          )
        }
      }
    }
  }  
}
