import java.text.SimpleDateFormat
version = ""
imageName = "backend"
devTag = "0.0-0"
CICD_PROJECT = "ci-cd"
DEV_PROJECT = "dev"
selectTag = ""
releaseTag = ""
tag = ""
UAT_PROJECT = "uat"

node('dotnet-31') {

  stage('Checkout Source') {
	checkout scm
  }
  
  stage('Prepare Variable') {
	script {
	  def dateFormat = new SimpleDateFormat("yyyyMMdd")
      def date = new Date()
      def releaseDate = (dateFormat.format(date))
      tag = releaseDate + "-" + env.BUILD_NUMBER
	}
  }
 
}
