import java.text.SimpleDateFormat
def selectTag
def releaseTag
def tag
def UAT_PROJECT = "uat"

node {
  def dateFormat = new SimpleDateFormat("yyyyMMdd")
  def date = new Date()
  def releaseDate = (dateFormat.format(date))
  tag = releaseDate + "-" + env.BUILD_NUMBER
  
}
pipeline {
  options {
    timeout(time: 30, unit: 'MINUTES')
  }
  environment {
    imageName="backend"
  }
  stages {  
    stage('Test') {
      steps {
        script {
		  echo "tag: ${tag}"
          openshift.withCluster() {
            openshift.withProject(env.UAT_PROJECT) {
              echo "chatchai hello world"
            }
          }
        }
      }
    }
  }
}
